# NumPy
* NumPy は、Python の行列演算ライブラリ
* Python 標準の List で行列を表現して、for ループで行列演算をすると大変遅い
* → 処理制御は Python で書いて、計算自体は C/Fortran で書かれた MKL / BLAST / LAPACK を呼び出せばよくね?
* というのが NumPy/SciPy

In [1]:
import numpy as np

# 行列データ ndarray
* numpy では、行列データは ndarray に格納する
* ndarray は C/Fortran ライブラリから使える形式で格納されている

In [2]:
lst = [[1,2,3],[4,5,6],[7,8,9]]
ndary = np.array(lst)
print ( type(lst) )
print ( lst )
print ( type(ndary) )
print ( ndary )

<class 'list'>
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# ndarray 同士の演算
* \+ \- \* 演算子が ndarray 向けに overload されている
* \* 演算子は、アダマール積 A⦿B　(i行ｊ列の要素同士の掛け算)
    * C = A \* B
* 行列の掛け算 A・B は、dot 関数を使う
    * C = A.dot(B)
    * C = np.dot(A,B)

In [3]:
mA = np.array([
    [1,3],
    [5,7]
])
mB = np.array([
    [2,4],
    [6,8]
])
print ("mA + mB = \n{}\n".format(mA + mB))
print ("mA - mB = \n{}\n".format(mA - mB))
print ("3 * mA = \n{}\n".format(3 * mA))
print ("mA * mB = \n{}\n".format(mA * mB))
print ("mA.dot(mB) = \n{}\n".format(mA.dot(mB)))
print ("np.dot(A,B) = \n{}\n".format(np.dot(mA,mB)))


mA + mB = 
[[ 3  7]
 [11 15]]

mA - mB = 
[[-1 -1]
 [-1 -1]]

3 * mA = 
[[ 3  9]
 [15 21]]

mA * mB = 
[[ 2 12]
 [30 56]]

mA.dot(mB) = 
[[20 28]
 [52 76]]

np.dot(A,B) = 
[[20 28]
 [52 76]]

