# NumPy
* NumPy は、Python の行列演算ライブラリ
* Python 標準の List で行列を表現して、for ループで行列演算をすると大変遅い
* → 処理制御は Python で書いて、計算自体は C/Fortran で書かれた MKL / BLAST / LAPACK を呼び出せばよくね?
* というのが NumPy/SciPy

In [1]:
import numpy as np

# 行列データ ndarray
* numpy では、行列データは ndarray に格納する
* ndarray は C/Fortran ライブラリから使える形式で格納されている

In [2]:
lst = [[1,2,3],[4,5,6],[7,8,9]]
ndary = np.array(lst)
print ( type(lst) )
print ( lst )
print ( type(ndary) )
print ( ndary )

<class 'list'>
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# ndarray ベクトル同士の演算
* ベクトルの掛け算 a・b は dot 関数を使う
* 内積 np.inner(a,b) → ベクトルa を b に投影した時の長さ。a の b 成分。2次元なら |a|cosθ (θは a と b が成す角) 
* 外積 np.cross(a,b) → a と b に直行するベクトルを求める
* テンソル積 np.outer(a,b) → a と b の要素を順列組み合わせでかけ合わせた行列

In [3]:
a = np.array([1,2,3])
b = np.array([1,-2,-1])
print ("a.dot(b) = \t{}\n".format(a.dot(b)))
print ("np.dot(a,b) = \t{}\n".format(np.dot(a,b)))
print ("np.inner(a,b) = \t{}\n".format(np.inner(a,b)))
print ("np.cross(a,b) = \t{}\n".format(np.cross(a,b)))
print ("np.outer(a,b) = \n{}\n".format(np.outer(a,b)))


a.dot(b) = 	-6

np.dot(a,b) = 	-6

np.inner(a,b) = 	-6

np.cross(a,b) = 	[ 4  4 -4]

np.outer(a,b) = 
[[ 1 -2 -1]
 [ 2 -4 -2]
 [ 3 -6 -3]]



# ndarray 行列同士の演算
* \+ \- \* 演算子が ndarray 向けに overload されている
* \* 演算子は、アダマール積 A⦿B　(i行ｊ列の要素同士の掛け算)
    * C = A \* B
* 行列の掛け算 A・B は、dot 関数を使う
    * C = A.dot(B)
    * C = np.dot(A,B)
* 転置は A.T
* == は要素同士を比較した　bool 型の行列を返す
* 行列全体の比較には np.array_equal 関数を使う

In [14]:
mA = np.array([
    [1,3],
    [5,7]
])
mB = np.array([
    [2,4],
    [6,8]
])
print ("mA + mB = \n{}\n".format(mA + mB))
print ("mA - mB = \n{}\n".format(mA - mB))
print ("3 * mA = \n{}\n".format(3 * mA))
print ("mA * mB = \n{}\n".format(mA * mB))
print ("mA.dot(mB) = \n{}\n".format(mA.dot(mB)))
print ("np.dot(A,B) = \n{}\n".format(np.dot(mA,mB)))
print ("mA == mB = \n{}\n".format(mA == mB))
print ("np.array_equal(mA, mB) = \n{}\n".format(np.array_equal(mA, mB)))

m = np.array([[1,2,3],[4,5,6]])
print ("m = \n{}".format(m))
print ("mT = \n{}".format(m.T))


mA + mB = 
[[ 3  7]
 [11 15]]

mA - mB = 
[[-1 -1]
 [-1 -1]]

3 * mA = 
[[ 3  9]
 [15 21]]

mA * mB = 
[[ 2 12]
 [30 56]]

mA.dot(mB) = 
[[20 28]
 [52 76]]

np.dot(A,B) = 
[[20 28]
 [52 76]]

mA == mB = 
[[False False]
 [False False]]

np.array_equal(mA, mB) = 
False

T = 
[[1 2 3]
 [4 5 6]]
mT = 
[[1 4]
 [2 5]
 [3 6]]


# ndarray の要素へのアクセス
* python の配列の添字は 0 はじまり
* ｎ次元配列の場合は、タプル (数字の組) で指定する
* 配列の一部を取り出すこともできる vec[start:end:step]

In [5]:
vec = np.array([0,1,2,3,4,5,6,7,8,9])
print ("vec= {}".format(vec))
print ("vec[2] = {}".format(vec[2]))
print ("vec[:7] = {}".format(vec[:7]))
print ("vec[3:] = {}".format(vec[3:]))
print ("vec[3:7] = {}".format(vec[3:7]))
print ("vec[3:7:2] = {}".format(vec[3:7:2]))
print("")
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print ("mat=\n{}".format(mat))
print ("mat[1]={}".format(mat[1]))
print ("mat[(0,0)]={}".format(mat[(0,0)]))
print ("mat[(0,2)]={}".format(mat[(0,2)]))
print ("mat[(2,0)]={}".format(mat[(2,0)]))



vec= [0 1 2 3 4 5 6 7 8 9]
vec[2] = 2
vec[:7] = [0 1 2 3 4 5 6]
vec[3:] = [3 4 5 6 7 8 9]
vec[3:7] = [3 4 5 6]
vec[3:7:2] = [3 5]

mat=
[[1 2 3]
 [4 5 6]
 [7 8 9]]
mat[1]=[4 5 6]
mat[(0,0)]=1
mat[(0,2)]=3
mat[(2,0)]=7


# ndarray を作成する
* 0行列や単位行列を作成する関数がある (np.zeros(), np.eye())
* 左上から 1,2,3,4... とやりたかったり、乱数の行列を作りたいときには、一旦 Vector (1次元) を作って、reshape(行,列) する
* とにかく、行列を格納するメモリ空間だけ確保したいときには np.empty([r,c]) を使う。★ 画像を処理するために巨大なメモリ空間を確保したいときなどにつかう　(0で初期化する時間がもったいない) ★

In [6]:
print( "要素が1〜10のVector \n{}".format(np.arange(10)) )
print( "要素が1〜10で2おきのVector \n{}".format(np.arange(1, 10, 2)) )
print( "要素が0〜１を5等分するVector \n{}".format(np.linspace(0, 1, 5)) )
print( "要素が0〜１(1を含まず)を5等分するVector \n{}".format(np.linspace(0, 1, 5, endpoint=False)) )
print( "要素がすべて1の3x3行列 \n{}".format(np.ones((3, 3))) )
print( "要素がすべて0の3x3行列 \n{}".format(np.zeros((3, 3))) )
print( "3行3列の単位行列 \n{}".format(np.eye(3)) )
print( "要素が乱数のVector \n{}".format(np.random.rand(12)) )
print( "要素が乱数の3x4行列 \n{}".format(np.random.rand(12).reshape(3,4)) )
print( "メモリ空間だけ確保したいとき(内容はmallocしたそのまま) \n{}".format(np.empty([2,5])))

要素が1〜10のVector 
[0 1 2 3 4 5 6 7 8 9]
要素が1〜10で2おきのVector 
[1 3 5 7 9]
要素が0〜１を5等分するVector 
[0.   0.25 0.5  0.75 1.  ]
要素が0〜１(1を含まず)を5等分するVector 
[0.  0.2 0.4 0.6 0.8]
要素がすべて1の3x3行列 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
要素がすべて0の3x3行列 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
3行3列の単位行列 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
要素が乱数のVector 
[0.95897797 0.63709072 0.93826254 0.22400341 0.57412257 0.42290777
 0.92176379 0.62838893 0.51164719 0.60957848 0.28688795 0.85618954]
要素が乱数の3x4行列 
[[0.7853633  0.57277131 0.96443818 0.75510072]
 [0.86808787 0.56703276 0.09116504 0.72112304]
 [0.38666512 0.76037714 0.96307498 0.58883631]]
メモリ空間だけ確保したいとき(内容はmallocしたそのまま) 
[[0.0e+000 4.9e-324 9.9e-324 1.5e-323 2.0e-323]
 [2.5e-323 3.0e-323 3.5e-323 4.0e-323 4.4e-323]]


# ndarray 自身の属性

* ndarray.flags : メモリへの各情景式
* ndarray.ndim : 次元
* ndarray.size : 要素数
* ndarray.shape : 形状(行数と列数のタプル)
* ndarray.dtype : 内部の数値型
* ndarray を作るときに、数値型を指定することもできる → np.array([[1,2],[3,4]], dtype=np.float)
  * bool(真偽), int, unit(unsigned int), float(浮動小数), complex(複素数)
  * int8 のようにビット数も指定できるけど、それは処理系に負かせたほうが良いでしょう
  * 型は np パッケージの定数を使ってもいいし、即値でもいい (結局同じことになる)
* 行列内部のデータ型の変換は matrix.astype( np.int ) のようにやるけど、これは matrix を変更しないことに注意。あたらしい ndarray が作られる


In [7]:
complex = np.array([[1.0+1.0j,0,0],[0,0,2.0+2.0j]])
print (complex)
print ("flags :\n {}".format(complex.flags))
print ("ndim : {}".format(complex.ndim))
print ("size : {}".format(complex.size))
print ("shape : {}".format(complex.shape))
print ("dtype : {}".format(complex.dtype))

matrix = np.array([[1,2],[3,4]], dtype=np.float)
print (matrix)
print ("dtype : {}".format(matrix.dtype))

matrix2 = matrix.astype( np.int )
print (matrix2)
print ("dtype : {}".format(matrix2.dtype))


[[1.+1.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 2.+2.j]]
flags :
   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
ndim : 2
size : 6
shape : (2, 3)
dtype : complex128
[[1. 2.]
 [3. 4.]]
dtype : float64
[[1 2]
 [3 4]]
dtype : int64


# 線形代数の処理
* numpy.linalg 配下に、逆行列、方程式の解を求める関数が用意されている
* numpy.linalg にある関数は、すべて scipy.linalg にあり、scipy.linalg の方が速いので、行列の線形代数処理は scipy.linalg を使う

# データの格納・読み出し
* numpy.io があるけど pandas を使うのが吉
* 画像を ndarray に読み出すこともできる