In [1]:
import oapackage
import numpy as np
from scipy import linalg

# OApackage で直交表を作る

$$
L_n(q^m) = OA (n, m, q, t) (t=q)
$$
* n : 大きさ、テスト回数
* m : 因子数 = テストデータの項目数
* q : 水準数 = テスト項目の値の種類
* t : 強さ = テスト項目の組み合わせ数

★　うまく行っていないっぽい

In [2]:
s=2 # 2 水準 {そのまま・増やす}
N=4 # 実験数 
ncols=3 # 3因子 {魚介だし・とんこつ・とりがら}
strength=ncols # 強度 = 任意の strength 個の因子の組み合わせがすべて洗い出されている
arrayclass=oapackage.arraydata_t(s, N, strength, ncols)
al=arrayclass.create_root()
al.showarray()

# 直交行列を numpy.ndarray 型で取りだす
print(al.getarray())
print(type(al.getarray()))

array: 
  0   0   0
  0   1   1
  1   0   0
  1   1   1
[[0 0 0]
 [0 1 1]
 [1 0 0]
 [1 1 1]]
<class 'numpy.ndarray'>


# 直交表と最小自乗推定で、パラメータの寄与度を計算する

In [3]:
m = al.getarray().astype(np.float).T
fixed = np.array([np.ones(4)]);
print(m)
print (fixed)
                 
A = (np.concatenate( (m, fixed) )).T
B = np.array([10.0,70.0,80.0,90.0])
print ("A=\n{}".format(A))
print ("B={}".format(B))
# least squares
C, resid, rank, sigma = linalg.lstsq(A, B)
print ("C={}".format(C))
print ("resid={}".format(resid))
print ("rank={}".format(rank))
print ("sigma={}".format(sigma))


[[0. 0. 1. 1.]
 [0. 1. 0. 1.]
 [0. 1. 0. 1.]]
[[1. 1. 1. 1.]]
A=
[[0. 0. 0. 1.]
 [0. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]
B=[10. 70. 80. 90.]
C=[45.  17.5 17.5 22.5]
resid=[]
rank=3
sigma=[2.79860888e+00 1.21472715e+00 8.32001383e-01 5.37821970e-17]


# 実験計画に使える直交表

In [4]:
def createOA (n, m, q) :
    print ("L{}({}^{})".format(n,m,q))
    arrayclass=oapackage.arraydata_t(m, n, q, q)
    al=arrayclass.create_root()
    al.showarray()
    
createOA(4,2,3)
createOA(12,2,11)
createOA(20,2,19)
createOA(24,2,23)
createOA(44,2,43)
createOA(60,2,59)
createOA(9,3,4)
createOA(27,3,13)
createOA(16,4,5)
createOA(64,4,21)
createOA(25,5,6)
createOA(50,5,12)

L4(2^3)
array: 
  0   0   0
  0   1   1
  1   0   0
  1   1   1
L12(2^11)
array: 
  0   0   0   0   0   0   0   0   0   0   0
  0   0   1   1   1   1   1   1   1   1   1
  0   0   0   0   0   0   0   0   0   0   0
  0   1   1   1   1   1   1   1   1   1   1
  0   1   0   0   0   0   0   0   0   0   0
  0   1   1   1   1   1   1   1   1   1   1
  1   0   0   0   0   0   0   0   0   0   0
  1   0   1   1   1   1   1   1   1   1   1
  1   0   0   0   0   0   0   0   0   0   0
  1   1   1   1   1   1   1   1   1   1   1
  1   1   0   0   0   0   0   0   0   0   0
  1   1   1   1   1   1   1   1   1   1   1
L20(2^19)
array: 
  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
  0   0   0   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
  0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
  0   0   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 

In [5]:
al=oapackage.exampleArray(3)
print(al.strength())
print(al.randomperm)
al.showarray()

3
<bound method array_link.randomperm of array_link: 32, 7>
array: 
  0   0   0   0   0   0   0
  0   0   0   0   0   0   0
  0   0   0   0   1   1   1
  0   0   0   0   1   1   1
  0   0   1   1   0   0   1
  0   0   1   1   0   0   1
  0   0   1   1   1   1   0
  0   0   1   1   1   1   0
  0   1   0   1   0   1   0
  0   1   0   1   0   1   1
  0   1   0   1   1   0   0
  0   1   0   1   1   0   1
  0   1   1   0   0   1   0
  0   1   1   0   0   1   1
  0   1   1   0   1   0   0
  0   1   1   0   1   0   1
  1   0   0   1   0   1   0
  1   0   0   1   0   1   1
  1   0   0   1   1   0   0
  1   0   0   1   1   0   1
  1   0   1   0   0   1   0
  1   0   1   0   0   1   1
  1   0   1   0   1   0   0
  1   0   1   0   1   0   1
  1   1   0   0   0   0   1
  1   1   0   0   0   0   1
  1   1   0   0   1   1   0
  1   1   0   0   1   1   0
  1   1   1   1   0   0   0
  1   1   1   1   0   0   0
  1   1   1   1   1   1   1
  1   1   1   1   1   1   1
