In [1]:
import numpy as np
from scipy import linalg

# 逆行列
* 行列式を求める linalg.det(A)
* 逆行列を求める linalg.inv(A)
    * 逆行列を求められない時 LinAlgError が発生する

In [2]:
A = np.array([[1,2,3],[9,4,3],[5,8,1]], dtype=float)
print("A=\n{}".format(A))
print("det(A) = {}".format(linalg.det(A)))
B = linalg.inv(A)
print("inverse A=\n{}".format(B))
print("A・inverseA=\n{}".format(np.dot(A,B)))

A=
[[1. 2. 3.]
 [9. 4. 3.]
 [5. 8. 1.]]
det(A) = 148.0
inverse A=
[[-0.13513514  0.14864865 -0.04054054]
 [ 0.04054054 -0.09459459  0.16216216]
 [ 0.35135135  0.01351351 -0.09459459]]
A・inverseA=
[[ 1.00000000e+00 -2.25514052e-17  2.77555756e-17]
 [ 1.66533454e-16  1.00000000e+00  1.38777878e-16]
 [ 5.55111512e-17 -8.15320034e-17  1.00000000e+00]]


逆行列が存在しない時に　LinAlgError が発生する仕様は、あまり信用しないほうが良いかも
$$
\begin{bmatrix}
1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 
\end{bmatrix} 
$$
は、逆行列が存在しないけど、LinAlgError が発生せずに誤った逆行列が計算される。当然 M・inv(M) は I(単位行列) にならない

In [3]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=float)
print("M=\n{}".format(M))
print("det(M) = {}".format(linalg.det(M)))
try :
    print("(wrong) inverse M=\n{}".format(linalg.inv(M)))
    print("** linalg.inv(M) don't throw LinAlgError **")
except LinAlgError as err:
    print(err)
print("M・inverseM= // it's not unit matrix \n{}".format(np.dot(M,linalg.inv(M))))

M=
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
det(M) = 0.0
inverse M=
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
** linalg.inv(M) don't throw LinAlgError **
M・inverseM=
[[ 0.  1.  0.]
 [-4.  2.  0.]
 [-4.  3.  2.]]
